In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split


In [ ]:
df=pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
pd.set_option('display.max_columns',None)
df.head()


In [ ]:
df.isnull().sum()

In [ ]:
X=df.iloc[:,:-1]   #[:,0:-1]
y=df['Age']
print(X.shape,y.shape)

In [ ]:
import numpy as np
np.set_printoptions(precision=2)

In [ ]:
df.replace('?',np.nan,inplace=True)

In [ ]:
df.head(2)
df.notnull()

In [ ]:
imputer = SimpleImputer()
cols=['Age',]
df[cols]= imputer.fit_transform(df[cols])
df.head(3)

In [ ]:
df.isnull().sum().sum()

In [ ]:
df.drop(['Cabin',],axis=1)
df.isnull().sum()
df.drop(['Embarked',],axis=1)
df.isnull().sum()

In [ ]:
df.head(8)

In [ ]:
df.isnull().sum()

In [ ]:
cols = ['Age']
imputer.fit_transform(df[cols])
df[cols]

In [ ]:
df['Age'].value_counts

In [ ]:
imp = SimpleImputer(strategy='most_frequent')
imp.fit_transform(df[['Embarked']])

one hot encoder

In [115]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

In [122]:
desig = OneHotEncoder(drop='first')
desig.fit(df[['Cabin']])

OneHotEncoder(drop='first')

In [123]:
dummy=desig.transform(df[['Cabin']]).toarray()

In [124]:
dummy

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [127]:
imp2 = SimpleImputer(strategy='most_frequent')
imp2.fit_transform(df[['Cabin']])

array([['B96 B98'],
       ['C85'],
       ['B96 B98'],
       ['C123'],
       ['B96 B98'],
       ['B96 B98'],
       ['E46'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['G6'],
       ['C103'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['D56'],
       ['B96 B98'],
       ['A6'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['C23 C25 C27'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B78'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       ['B96 B98'],
       [

In [130]:
df['Cabin'] = imp2.fit_transform(df[['Cabin']])

In [132]:
df['Cabin'].value_counts

<bound method IndexOpsMixin.value_counts of 0      B96 B98
1          C85
2      B96 B98
3         C123
4      B96 B98
        ...   
886    B96 B98
887        B42
888    B96 B98
889       C148
890    B96 B98
Name: Cabin, Length: 891, dtype: object>

In [142]:
imp = SimpleImputer(strategy='most_frequent')
imp.fit_transform(df[['Age']])

array([[22.  ],
       [38.  ],
       [26.  ],
       [35.  ],
       [35.  ],
       [24.  ],
       [54.  ],
       [ 2.  ],
       [27.  ],
       [14.  ],
       [ 4.  ],
       [58.  ],
       [20.  ],
       [39.  ],
       [14.  ],
       [55.  ],
       [ 2.  ],
       [24.  ],
       [31.  ],
       [24.  ],
       [35.  ],
       [34.  ],
       [15.  ],
       [28.  ],
       [ 8.  ],
       [38.  ],
       [24.  ],
       [19.  ],
       [24.  ],
       [24.  ],
       [40.  ],
       [24.  ],
       [24.  ],
       [66.  ],
       [28.  ],
       [42.  ],
       [24.  ],
       [21.  ],
       [18.  ],
       [14.  ],
       [40.  ],
       [27.  ],
       [24.  ],
       [ 3.  ],
       [19.  ],
       [24.  ],
       [24.  ],
       [24.  ],
       [24.  ],
       [18.  ],
       [ 7.  ],
       [21.  ],
       [49.  ],
       [29.  ],
       [65.  ],
       [24.  ],
       [21.  ],
       [28.5 ],
       [ 5.  ],
       [11.  ],
       [22.  ],
       [38.  ],
       [

In [143]:
df['Age'] = imp.fit_transform(df[['Age']])

In [144]:
df.head(7)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male  24.0      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   

   Parch            Ticket     Fare    Cabin  
0      0         A/5 21171   7.2500  B96 B98  
1      0          PC 17599  71.2833      C85  
2      0  STON/O2. 3101282   7.9250  B96 B98  
3      0            113803  53.1000     C123  
4      0            373450   8.0500  B96 B98  
5      0            330877   8.4583  B96 B98  
6      0             17463  51.8625      E46

In [147]:
df['Age'].unique()

array([22.  , 38.  , 26.  , 35.  , 24.  , 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 46.  , 59.  , 71.  ,
       37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 , 51.  ,
       55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  , 45.5 ,
       20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  , 60.  ,
       10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  , 70.  ,
       24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

In [148]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
dtype: int64